apiVersion: v1
data:
  FACEBOOK_APP_ID: 
  FACEBOOK_APP_SECRET: 
  GOOGLE_CLIENT_ID: 
  GOOGLE_CLIENT_SECRET: 
  JWT_SECRET: 
  SESSION_SECRET: 
  TWITTER_CONSUMER_KEY: 
  TWITTER_CONSUMER_SECRET: 
kind: Secret
metadata:
  name: account-gateway
type: Opaque
