apiVersion: v1
kind: ReplicationController
metadata:
  name: account-gateway
spec:
  replicas: 1
  selector:
    app: account-gateway
  template:
    metadata:
      labels:
        app: account-gateway
    spec:
      containers:
        - name: account-gateway
          image: totem-gdn/account-gateway:latest # FIXME
          command:
            - "node dist/main.js"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
            - name: BASE_URL
            - name: KEYSTORE_HOST
            - name: KEYSTORE_PORT
            - name: SESSION_SECRET
            - name: JWT_SECRET
            - name: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
            - name: TWITTER_CONSUMER_KEY
            - name: TWITTER_CONSUMER_SECRET
            - name: FACEBOOK_APP_ID
            - name: FACEBOOK_APP_SECRET
